import * as THREE from '../vendor/three.module.js?v=052';
export const CANNON=Object.freeze({speed:180,lifetime:4,cooldown:3,directDamage:3510,splashRadius:22,splashDamage:235,pool:6});
export function createCannonRounds({scene,glowTexture}){
 const root=new THREE.Group();root.name='Slag cannon projectiles and pressure trails';scene.add(root);
 const geo=new THREE.IcosahedronGeometry(.72,2),p=geo.attributes.position;
 for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),k=1+.11*Math.sin(x*13+y*9+z*7);p.setXYZ(i,x*k,y*k,z*k);}geo.computeVertexNormals();
 const mat=new THREE.MeshStandardMaterial({color:0x29221a,roughness:.78,metalness:.35,emissive:0xff5a08,emissiveIntensity:2.4});
 mat.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vSlag;');s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvSlag=position;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vSlag;');s.fragmentShader=s.fragmentShader.replace('#include <emissivemap_fragment>','#include <emissivemap_fragment>\nfloat crack=1.-smoothstep(.025,.105,abs(sin(vSlag.x*12.+sin(vSlag.y*11.))*sin(vSlag.z*14.+vSlag.y*7.)));totalEmissiveRadiance*=crack;');};mat.customProgramCacheKey=()=> 'original-slag-round-1';
 const rounds=[];
 for(let i=0;i<CANNON.pool;i++){const group=new THREE.Group();group.name=`Slag round ${i}`;const body=new THREE.Mesh(geo,mat);group.add(body);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:0xff8c25,transparent:true,opacity:.78,blending:THREE.AdditiveBlending,depthWrite:false}));halo.scale.set(3.1,3.1,1);group.add(halo);group.visible=false;root.add(group);rounds.push({group,body,halo,active:false,pos:new THREE.Vector3(),prev:new THREE.Vector3(),vel:new THREE.Vector3(),life:0,age:0,trailClock:0,record:null});}
 const count=128,states=Array.from({length:count},()=>({life:0,total:.45,pos:new THREE.Vector3(),size:1})),positions=new Float32Array(count*3),sizes=new Float32Array(count),fades=new Float32Array(count),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));g.setAttribute('size',new THREE.BufferAttribute(sizes,1));g.setAttribute('fade',new THREE.BufferAttribute(fades,1));let cursor=0;
 const trail=new THREE.Points(g,new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uReduced:{value:0}},vertexShader:'attribute float size;attribute float fade;varying float vFade;void main(){vFade=fade;vec4 mv=modelViewMatrix*vec4(position,1.);gl_PointSize=clamp(size*620./max(1.,-mv.z),0.,80.);gl_Position=projectionMatrix*mv;}',fragmentShader:'varying float vFade;void main(){float d=length(gl_PointCoord-.5)*2.;float a=pow(max(0.,1.-d),1.7)*vFade;if(a<.008)discard;vec3 c=mix(vec3(.20,.16,.12),vec3(1.,.48,.12),pow(vFade,6.));gl_FragColor=vec4(c,a*.7);}'}));trail.frustumCulled=false;root.add(trail);
 function emit(at){const s=states[cursor++%count];s.pos.copy(at);s.life=s.total=.44;s.size=1.4;}
 function update(dt,reduced=false){for(const b of rounds)if(b.active){b.age+=dt;b.body.rotation.set(b.age*3.8,b.age*5.3,b.age*2.4);b.halo.material.opacity=reduced?.34:.78;b.trailClock-=dt;if(b.trailClock<=0){emit(b.pos);b.trailClock=reduced?.10:.035;}}for(let i=0;i<count;i++){const s=states[i];s.life=Math.max(0,s.life-dt);s.pos.y+=dt*.8;s.pos.toArray(positions,i*3);sizes[i]=s.life>0?s.size+(1-s.life/s.total)*2.8:0;fades[i]=s.life/s.total;}g.attributes.position.needsUpdate=true;g.attributes.size.needsUpdate=true;g.attributes.fade.needsUpdate=true;}
 function reset(){cursor=0;for(const b of rounds){b.active=false;b.life=b.age=b.trailClock=0;b.group.visible=false;b.body.rotation.set(0,0,0);b.record=null;}for(const s of states)s.life=0;update(0);}
 return{root,rounds,update,reset,stats:()=>({active:rounds.filter(b=>b.active).length,trails:states.filter(s=>s.life>0).length,roundCap:CANNON.pool,trailCap:count})};
}
